# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'QTModuleUtils' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    use_frameworks!
    
    # Pods for QTModuleUtils
    
    pod 'ReactiveObjC','3.1.0'
    pod 'YYModel','1.0.4'
    pod 'PureLayout'
    pod 'YYImage'
    pod 'MBProgressHUD'
    pod 'SwipeView'
    
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
        end
    end
end
